name: CI

on: [push]

env:
  DOCKER_REGISTRY: registry.walhall.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: |
        echo Commit: ${GITHUB_SHA}
        echo Branch: ${GITHUB_REF##*/}
        echo ::set-output name=COMMIT::${GITHUB_SHA}
        echo ::set-output name=BRANCH::${GITHUB_REF##*/}
  
    - name: Publish image to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ env.GITHUB_REPOSITORY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ env.DOCKER_REGISTRY }}
        tags: "latest,${{ steps.get_version.outputs.COMMIT }}"
        
    - name: Notify Humanitec
      run: |
        echo "Notifying humanitec about new push for ${GITHUB_REPOSITORY}"
        echo curl -H "Content-Type:application/json" -d "{\"commit\":\"${GITHUB_SHA}\",\"branch\":\"${GITHUB_REF##*/}\",\"tags\":[],\"image\":\"registry.walhall.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}\"}" "https://dev-api.walhall.io/orgs/${GITHUB_REPOSITORY%/*}/modules/${GITHUB_REPOSITORY#*/}/builds"
        curl -H "Content-Type:application/json" -d "{\"commit\":\"${GITHUB_SHA}\",\"branch\":\"${GITHUB_REF##*/}\",\"tags\":[],\"image\":\"registry.walhall.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}\"}" "https://dev-api.walhall.io/orgs/${GITHUB_REPOSITORY%/*}/modules/${GITHUB_REPOSITORY#*/}/builds"
        
