name: CI

on: [push]

env:
  DOCKER_REGISTRY: registry.walhall.io

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')

    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: |
        echo Commit: ${GITHUB_SHA}
        echo Branch: ${GITHUB_REF##*/}
        echo ::set-output name=COMMIT::${GITHUB_SHA}
        echo ::set-output name=BRANCH::${GITHUB_REF##*/}
        echo curl -H "Content-Type:application/json" -d '{"commit":"${GITHUB_SHA}","branch":"${GITHUB_REF##*/}","tags":[],"image":"registry.walhall.io/corporate-org/simplest-app:${GITHUB_SHA}"}' "https://dev-api.walhall.io/orgs/corporate-org/modules/simplest-app/builds"
        curl -H "Content-Type:application/json" -d '{"commit":"${GITHUB_SHA}","branch":"${GITHUB_REF##*/}","tags":[],"image":"registry.walhall.io/corporate-org/simplest-app:${GITHUB_SHA}"}' "https://dev-api.walhall.io/orgs/corporate-org/modules/simplest-app/builds"
  
    - name: Publish image to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: corporate-org/simplest-app
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ env.DOCKER_REGISTRY }}
        tags: "latest,${{ steps.get_version.outputs.COMMIT }}"

